"""init

Revision ID: ffc26032241f
Revises: 
Create Date: 2026-02-14 17:51:52.776544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc26032241f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_owner_id'), 'notes', ['owner_id'], unique=False)
    op.drop_constraint(op.f('notes_owner_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_owner_id_fkey'), 'notes', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_notes_owner_id'), table_name='notes')
    # ### end Alembic commands ###
